title: Helene Schmehl
logo: /images/Screenshot 2025-02-11 at 16.40.08.png
#description: Second-year M.Sc. student in Computational Linguistics, math teacher, German teacher, curriculum designer
show_downloads: true
theme: jekyll-theme-minimal
