title: Helene Schmehl
logo: /images/me.jpg
#description: Second-year M.Sc. student in Computational Linguistics, math teacher, German teacher, curriculum designer
show_downloads: true
theme: jekyll-theme-minimal
